exclude_paths:
  - '/vendor/*'

engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: 'php'
      standard: 'PEAR,PSR1'
  phpmd:
    enabled: true
    config:
      file_extensions: 'php'
      rulesets: 'unusedcode'

ratings:
  paths:
    - '**.php'
